dist: trusty
language: cpp
script:
    mkdir build && cd build
    cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    cmake --build .
    ./hello

env:
    BUILD_TYPE=Release COMPILER=g++-4.9
    BUILD_TYPE=Release COMPILER=g++-5
    BUILD_TYPE=Release COMPILER=g++-6
    BUILD_TYPE=Debug COMPILER=g++-4.9
    BUILD_TYPE=Debug COMPILER=g++-5
    BUILD_TYPE=Debug COMPILER=g++-6

addons:
    apt:
        sources:
            ubuntu-toolchain-r-test
        packages:
            g++-4.9
            g++-5
            g++-6